services:


# ----------------------------------------------------------------------------------------------------------------------
#  Services
# ----------------------------------------------------------------------------------------------------------------------

    neo4j_sync.neo4j_client:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jClient
        public: true
        tags:
            - name: 'monolog.logger'
              channel: 'neo4j_sync'
        arguments:
            - '@logger'

    Syndesi\Neo4jSyncBundle\Service\Neo4jClient: '@neo4j_sync.neo4j_client'


    neo4j_sync.neo4j_client_factory:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jClientFactory
        public: true

    Syndesi\Neo4jSyncBundle\Service\Neo4jClientFactory: '@neo4j_sync.neo4j_client_factory'


# ----------------------------------------------------------------------------------------------------------------------
#  Event subscribers
# ----------------------------------------------------------------------------------------------------------------------

    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostFlushSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostFlushSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'


    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'


    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'


    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'


# ----------------------------------------------------------------------------------------------------------------------
#  Commands
# ----------------------------------------------------------------------------------------------------------------------
