services:


# ----------------------------------------------------------------------------------------------------------------------
#  Services
# ----------------------------------------------------------------------------------------------------------------------

    neo4j_sync.neo4j_client:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jClient
        public: true
        tags: [
            {
                name: 'monolog.logger',
                channel: 'neo4j_sync'
            }
        ]
        arguments:
            - '@logger'

    Syndesi\Neo4jSyncBundle\Service\Neo4jClient: '@neo4j_sync.neo4j_client'

    neo4j_sync.neo4j_client_factory:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jClientFactory
        public: true
        arguments:
#            - '@neo4j_sync.entity_data_object_service' # todo

    Syndesi\Neo4jSyncBundle\Service\Neo4jClientFactory: '@neo4j_sync.neo4j_client_factory'


    neo4j_sync.neo4j_normalizer:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jNormalizer
        public: false

    Syndesi\Neo4jSyncBundle\Service\Neo4jNormalizer: '@neo4j_sync.neo4j_normalizer'


    neo4j_sync.entity_reader:
        class: Syndesi\Neo4jSyncBundle\Service\EntityReader
        public: false
        arguments:
            - '@neo4j_sync.neo4j_normalizer'
    
    Syndesi\Neo4jSyncBundle\Service\EntityReader: '@neo4j_sync.entity_reader'


    neo4j_sync.neo4j_statement_helper:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jStatementHelper
        public: false
        arguments:
            - '@neo4j_sync.entity_reader'
    
    Syndesi\Neo4jSyncBundle\Service\Neo4jStatementHelper: '@neo4j_sync.neo4j_statement_helper'


# ----------------------------------------------------------------------------------------------------------------------
#  Event subscribers
# ----------------------------------------------------------------------------------------------------------------------

    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostFlushSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostFlushSubscriber
        public: false
        tags: [
            'doctrine.event_subscriber',
#            {
#                name: 'monolog.logger',
#                channel: 'neo4j_sync'
#            }
        ]
        arguments:
            - '@neo4j_sync.neo4j_client'
#            - '@logger'

    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistSubscriber
        public: false
        tags: [ 'doctrine.event_subscriber' ]
        arguments:
            - '@neo4j_sync.neo4j_client'
            - '@neo4j_sync.entity_reader'
            - '@neo4j_sync.neo4j_statement_helper'


    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateSubscriber
        public: false
        tags: [ 'doctrine.event_subscriber' ]
        arguments:
            - '@neo4j_sync.neo4j_client'
            - '@neo4j_sync.entity_reader'
            - '@neo4j_sync.neo4j_statement_helper'


    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveSubscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveSubscriber
        public: false
        tags: [ 'doctrine.event_subscriber' ]
        arguments:
            - '@neo4j_sync.neo4j_client'
            - '@neo4j_sync.entity_reader'
            - '@neo4j_sync.neo4j_statement_helper'


# ----------------------------------------------------------------------------------------------------------------------
#  Commands
# ----------------------------------------------------------------------------------------------------------------------

    neo4j_sync.command.db.delete:
        class: Syndesi\Neo4jSyncBundle\Command\DatabaseDeleteCommand
        public: true
        tags: [ 'console.command' ]
        arguments:
            - '@neo4j_sync.neo4j_client'

    Syndesi\Neo4jSyncBundle\Command\DatabaseDeleteCommand: '@neo4j_sync.command.db.delete'

    neo4j_sync.command.db.sync:
        class: Syndesi\Neo4jSyncBundle\Command\DatabaseSyncCommand
        public: true
        tags: [ 'console.command' ]
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@neo4j_sync.neo4j_client'
            - '@neo4j_sync.neo4j_statement_helper'
            - '@neo4j_sync.entity_reader'

    Syndesi\Neo4jSyncBundle\Command\DatabaseSyncCommand: '@neo4j_sync.command.db.sync'
