services:


# ----------------------------------------------------------------------------------------------------------------------
#  Services
# ----------------------------------------------------------------------------------------------------------------------

    neo4j_sync.neo4j_client:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jClient
        public: true
        tags:
            - name: 'monolog.logger'
              channel: 'neo4j_sync'
        arguments:
            - '@logger'

    Syndesi\Neo4jSyncBundle\Service\Neo4jClient: '@neo4j_sync.neo4j_client'


    neo4j_sync.neo4j_client_factory:
        class: Syndesi\Neo4jSyncBundle\Service\Neo4jClientFactory
        public: true

    Syndesi\Neo4jSyncBundle\Service\Neo4jClientFactory: '@neo4j_sync.neo4j_client_factory'


# ----------------------------------------------------------------------------------------------------------------------
#  Event subscribers
# ----------------------------------------------------------------------------------------------------------------------

    neo4j_sync.event_listener.doctrine_post_flush_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostFlushSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'
    
    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostFlushSubscriber: '@neo4j_sync.event_listener.doctrine_post_flush_subscriber'


    neo4j_sync.event_listener.doctrine_post_persist_node_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistNodeSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'
    
    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistNodeSubscriber: '@neo4j_sync.event_listener.doctrine_post_persist_node_subscriber'


    neo4j_sync.event_listener.doctrine_post_persist_relation_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistRelationSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'

    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostPersistRelationSubscriber: '@neo4j_sync.event_listener.doctrine_post_persist_relation_subscriber'
    

    neo4j_sync.event_listener.doctrine_post_update_node_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateNodeSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'
    
    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateNodeSubscriber: '@neo4j_sync.event_listener.doctrine_post_update_node_subscriber'


    neo4j_sync.event_listener.doctrine_post_update_relation_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateRelationSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'
    
    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePostUpdateRelationSubscriber: '@neo4j_sync.event_listener.doctrine_post_update_relation_subscriber'


    neo4j_sync.event_listener.doctrine_pre_remove_node_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveNodeSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'
    
    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveNodeSubscriber: '@neo4j_sync.event_listener.doctrine_pre_remove_node_subscriber'


    neo4j_sync.event_listener.doctrine_pre_remove_relation_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveRelationSubscriber
        public: false
        tags:
            - 'doctrine.event_subscriber'
        arguments:
            - '@neo4j_sync.neo4j_client'
    
    Syndesi\Neo4jSyncBundle\EventListener\DoctrinePreRemoveRelationSubscriber: '@neo4j_sync.event_listener.doctrine_pre_remove_relation_subscriber'


    neo4j_sync.event_listener.get_all_indices_subscriber:
        class: Syndesi\Neo4jSyncBundle\EventListener\GetAllIndicesSubscriber
        public: false
        tags:
            - kernel.event_subscriber
        arguments:
            - '@doctrine.orm.entity_manager'
    
    Syndesi\Neo4jSyncBundle\EventListener\GetAllIndicesSubscriber: '@neo4j_sync.event_listener.get_all_indices_subscriber'


# ----------------------------------------------------------------------------------------------------------------------
#  Commands
# ----------------------------------------------------------------------------------------------------------------------

    neo4j_sync.command.db.purge:
        class: Syndesi\Neo4jSyncBundle\Command\DatabasePurgeCommand
        public: true
        tags:
            - 'console.command'
        arguments:
            - '@neo4j_sync.neo4j_client'

    Syndesi\Neo4jSyncBundle\Command\DatabasePurgeCommand: '@neo4j_sync.command.db.purge'


    neo4j_sync.command.db.sync:
        class: Syndesi\Neo4jSyncBundle\Command\DatabaseSyncCommand
        public: true
        tags:
            - 'console.command'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@neo4j_sync.neo4j_client'

    Syndesi\Neo4jSyncBundle\Command\DatabaseSyncCommand: '@neo4j_sync.command.db.sync'


    neo4j_sync.command.index.list:
        class: Syndesi\Neo4jSyncBundle\Command\IndexListCommand
        public: true
        tags:
            - 'console.command'
        arguments:
            - '@neo4j_sync.neo4j_client'
            - '@event_dispatcher'

    Syndesi\Neo4jSyncBundle\Command\IndexListCommand: '@neo4j_sync.command.index.list'


    neo4j_sync.command.index.sync:
        class: Syndesi\Neo4jSyncBundle\Command\IndexSyncCommand
        public: true
        tags:
            - 'console.command'
        arguments:
            - '@neo4j_sync.neo4j_client'
            - '@event_dispatcher'

    Syndesi\Neo4jSyncBundle\Command\IndexSyncCommand: '@neo4j_sync.command.index.sync'


    neo4j_sync.command.index.purge:
        class: Syndesi\Neo4jSyncBundle\Command\IndexPurgeCommand
        public: true
        tags:
            - 'console.command'
        arguments:
            - '@neo4j_sync.neo4j_client'

    Syndesi\Neo4jSyncBundle\Command\IndexPurgeCommand: '@neo4j_sync.command.index.purge'
