
name: Unit Tests

on: [push, fork, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "Running unit tests for PHP ${{ matrix.php-version }}"
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.1']
        
        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: php-actions/composer@v6
              with:
                  progress: yes
                  php_version: ${{ matrix.php-version }}
                  php_extensions: xdebug
                  version: 2
            - uses: php-actions/phpunit@v3
              with:
                  version: 9
                  configuration: phpunit.xml.dist
                  php_version: ${{ matrix.php-version }}
                  php_extensions: xdebug
                  bootstrap: vendor/autoload.php
