
name: YML lint

on: [push, fork, pull_request]

jobs:
    yml-lint:
        runs-on: ubuntu-latest
        name: "YML lint"
        strategy:
            fail-fast: false
            
        steps:
            - uses: actions/checkout@v2
            - uses: addnab/docker-run-action@v3
              with:
                  image: cytopia/yamllint
                  options: -v $(pwd):/data
                  shell: bash
                  run: .
